import {test,expect,type Page} from '@playwright/test'
async function login(page:Page,role:string){await page.goto('/');await page.getByLabel('Email address').fill(role+'@demo.pac.test');await page.getByLabel('Password',{exact:true}).fill('Demo123!Change');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible()}
async function switchUser(page:Page,role:string){await page.getByRole('button',{name:'Sign out'}).click();await login(page,role)}
test('discussion persists and alerts assigned supervisor',async({page})=>{
 await login(page,'student');await page.getByRole('button',{name:'My journey',exact:true}).click();await page.getByRole('tab',{name:'Submissions',exact:true}).click()
 await page.getByLabel('Academic question or comment').fill('Pitch test: should the sampling frame include offline service users?')
 await page.getByRole('button',{name:'Post comment',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Comment posted'})).toBeVisible()
 await switchUser(page,'supervisor');await page.getByRole('button',{name:/^Notifications/}).click()
 const card=page.locator('.notification-card').filter({hasText:'New discussion reply'}).first()
 await card.getByRole('button',{name:'Open related work'}).click();await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.getByText('Pitch test: should the sampling frame include offline service users?',{exact:true})).toBeVisible()
})
test('next action follow-up reaches recipient and supports reply',async({page})=>{
 await login(page,'dean');await page.getByRole('button',{name:'Reports',exact:true}).click()
 await page.locator('tr').filter({hasText:'Amina Wanjiku'}).getByRole('button',{name:/Follow up/}).click()
 await page.getByLabel('Send to').selectOption('50000000-0000-0000-0000-000000000002')
 await page.getByLabel('Follow-up message').fill('Pitch follow-up: please confirm your next review date.')
 await page.getByRole('button',{name:'Send in-app notification'}).click();await expect(page.getByRole('status').filter({hasText:'Sent in-app'})).toBeVisible()
 await page.getByRole('button',{name:'Close',exact:true}).click();await switchUser(page,'supervisor')
 await page.getByRole('button',{name:/^Notifications/}).click();const card=page.locator('.notification-card').filter({hasText:'Pitch follow-up:'})
 await expect(card).toBeVisible();await card.getByRole('button',{name:'Mark read'}).click();await expect(card.locator('.status-pill')).toHaveText('read')
 await card.getByRole('button',{name:'Open related work'}).click();await page.getByLabel('Follow-up student').selectOption('60000000-0000-0000-0000-000000000001')
 await page.getByLabel('Send to').selectOption('50000000-0000-0000-0000-000000000008');await page.getByLabel('Follow-up message').fill('Pitch reply: the review is scheduled for Friday.');await page.getByRole('button',{name:'Send in-app notification'}).click()
 await expect(page.getByRole('status').filter({hasText:'Sent in-app'})).toBeVisible()
 await switchUser(page,'dean');await page.getByRole('button',{name:/^Notifications/}).click();await expect(page.getByText('Pitch reply: the review is scheduled for Friday.',{exact:true})).toBeVisible()
})
test('staff student groups and concept decision history are linked',async({page})=>{
 await login(page,'dean');await page.getByRole('button',{name:'Student milestones',exact:true}).click()
 const groups=page.locator('.student-group');const names=await groups.locator('summary strong').allTextContents();expect(names).toEqual([...names].sort((a,b)=>a.localeCompare(b)))
 const amina=groups.filter({hasText:'Amina Wanjiku'});await amina.locator('summary').click();await expect(amina.getByText('25%',{exact:true})).toBeVisible();await expect(amina.getByRole('button',{name:'Open milestone'})).toHaveCount(8)
 await page.getByRole('button',{name:'Research concepts',exact:true}).click()
 const approved=page.locator('.record-card').filter({hasText:'Digital service adoption among small businesses'})
 await expect(approved.locator('.status-pill')).toHaveText('approved');await expect(approved).toContainText('Dr. Samuel Otieno')
 await expect(page.locator('.record-card').filter({hasText:'A national platform'}).locator('.status-pill')).toHaveText('declined')
})
test('leave request opens, records a decision and notifies student',async({page})=>{
 await login(page,'newstudent');await page.getByRole('button',{name:'Leave & extensions',exact:true}).click();await page.getByRole('button',{name:'Request leave',exact:true}).click()
 await page.getByLabel('Start date',{exact:true}).fill('2026-10-05');await page.getByLabel('End date',{exact:true}).fill('2026-10-09');await page.getByLabel('Return date',{exact:true}).fill('2026-10-10');await page.getByLabel('Reason category').fill('Study arrangements');await page.getByLabel('Private explanation').fill('Test private explanation not for public dashboards.')
 await page.getByRole('button',{name:'Submit request'}).click();await expect(page.getByText('Request submitted. An in-app alert was sent to the academic team.')).toBeVisible()
 await switchUser(page,'dean');await page.getByRole('button',{name:'Leave & extensions',exact:true}).click();await page.locator('.record-card').filter({hasText:'Brian Kiptoo'}).getByRole('button',{name:'Open request'}).click()
 await expect(page.getByRole('dialog')).toContainText('Study arrangements');await expect(page.getByText('Test private explanation not for public dashboards.')).toHaveCount(0)
 await page.getByLabel('Decision',{exact:true}).selectOption('declined');await page.getByLabel('Decision reason (at least 8 characters)').fill('Please confirm the proposed arrangements with the programme office.')
 await page.getByRole('button',{name:'Record decision'}).click();await expect(page.getByText('Decision saved. The student has been notified in-app.')).toBeVisible()
 await switchUser(page,'newstudent');await page.getByRole('button',{name:/^Notifications/}).click();await expect(page.getByRole('heading',{name:'Leave request: declined',exact:true})).toBeVisible()
})

test('provisioned newcomer requests a supervisor and sees the confirmed assignment',async({page})=>{
 await login(page,'newstudent');await page.getByRole('button',{name:'Choose supervisor'}).click()
 await page.locator('.record-card').filter({hasText:'Dr. Samuel Otieno'}).getByRole('button',{name:'Request supervision'}).click()
 await page.getByLabel('Position',{exact:true}).selectOption('primary');await page.getByLabel('Research interests and request').fill('Interested in information systems and digital inclusion.');await page.getByRole('button',{name:'Send request'}).click()
 await expect(page.getByText('Supervision request sent.')).toBeVisible();await switchUser(page,'supervisor');await page.getByRole('button',{name:'Supervision',exact:true}).click()
 await page.locator('.record-card').filter({hasText:'Brian Kiptoo'}).getByRole('button',{name:'Open request'}).click();await page.getByLabel('Response',{exact:true}).selectOption('accepted');await page.getByLabel('Response reason').fill('Research interests align and capacity is available.');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click()
 await expect(page.getByText('Response recorded.')).toBeVisible();await switchUser(page,'dean');await page.getByRole('button',{name:'Supervision',exact:true}).click()
 await page.locator('.record-card').filter({hasText:'Brian Kiptoo'}).getByRole('button',{name:'Open request'}).click();await page.getByLabel('Allocation note').fill('Confirmed within programme eligibility and capacity.');await page.getByRole('button',{name:'Confirm allocation'}).click()
 await expect(page.getByText('Allocation confirmed.')).toBeVisible();await switchUser(page,'newstudent');await page.getByRole('button',{name:'Supervision',exact:true}).click()
 await expect(page.locator('.message').filter({hasText:'Confirmed assignment'})).toContainText('Dr. Samuel Otieno')
})
