import {test,expect,type Page} from '@playwright/test'
import path from 'node:path'
async function login(page:Page,role:string){await page.goto('/');await page.getByLabel('Email address').fill(role+'@demo.pac.test');await page.getByLabel('Password',{exact:true}).fill('Demo123!Change');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible()}
async function switchUser(page:Page,role:string){await page.getByRole('button',{name:'Sign out'}).click();await login(page,role)}
test('provided PAC logo appears on login and authenticated workspace',async({page})=>{await page.goto('/');const logo=page.locator('.login-brand img.pac-logo');await expect(logo).toHaveAttribute('src','/pac-university-logo.png');expect(await logo.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBeTruthy();await login(page,'dean');await expect(page.locator('header img.pac-logo')).toBeVisible()})
test('request opens, replies persist and coordinator resolves it',async({page})=>{
 await login(page,'student');await page.getByRole('button',{name:'Requests & support',exact:true}).click();await page.getByRole('button',{name:'New request'}).click();await page.getByLabel('Category',{exact:true}).selectOption('administrative clearance');await page.getByLabel('What is happening?').fill('Please clarify the current administrative clearance sequence.');await page.getByRole('button',{name:'Send request'}).click();await expect(page.getByText('Your support request has been recorded.')).toBeVisible();await page.locator('.record-card').filter({hasText:'Please clarify the current administrative clearance sequence.'}).getByRole('button',{name:'Open request'}).click();await page.getByLabel('Reply',{exact:true}).fill('I can bring the signed form on Monday.');await page.getByRole('button',{name:'Send reply'}).click();await expect(page.locator('.message p').filter({hasText:'I can bring the signed form on Monday.'})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await switchUser(page,'coordinator');await page.getByRole('button',{name:'Interventions',exact:true}).click();await page.locator('.record-card').filter({hasText:'Please clarify the current administrative clearance sequence.'}).getByRole('button',{name:'Open request'}).click();await expect(page.locator('.message p').filter({hasText:'I can bring the signed form on Monday.'})).toBeVisible();await page.getByLabel('Follow-up action',{exact:true}).fill('Verify signed clearance form');await page.getByLabel('Due date',{exact:true}).fill('2026-10-10');await page.getByRole('button',{name:'Add follow-up'}).click();await expect(page.getByText('Verify signed clearance form',{exact:true})).toBeVisible();await page.getByLabel('Case status').selectOption('resolved');await page.getByLabel('Resolution / status explanation').fill('The programme office confirmed and recorded clearance.');await page.getByRole('button',{name:'Update case'}).click();await expect(page.getByText('Resolution: The programme office confirmed and recorded clearance.')).toBeVisible()
})
test('student concept reaches supervisor and feedback returns',async({page})=>{
 await login(page,'student');await page.getByRole('button',{name:'Research concepts',exact:true}).click();await page.getByRole('button',{name:'Submit concept',exact:true}).click();await page.getByLabel('Proposed title').fill('Digital county service access');await page.getByLabel('Problem statement').fill('Residents face uneven access to digital services across county offices.');await page.getByLabel('Research objectives').fill('Identify barriers and assess service uptake among residents.');await page.getByLabel('Proposed methodology').fill('A mixed methods survey and interviews with service users.');await page.getByRole('dialog').getByRole('button',{name:'Submit concept',exact:true}).click();await expect(page.getByText('Concept submitted for supervisor review.')).toBeVisible();await switchUser(page,'supervisor');await page.getByRole('button',{name:'Research concepts',exact:true}).click();await page.locator('.record-card').filter({hasText:'Digital county service access'}).getByRole('button',{name:'Review concept'}).click();await page.getByLabel('Decision',{exact:true}).selectOption('changes_requested');await page.getByLabel('Feedback',{exact:true}).fill('Narrow your sampling frame to two county offices.');await page.getByRole('button',{name:'Record decision'}).click();await switchUser(page,'student');await page.getByRole('button',{name:'Research concepts',exact:true}).click();await expect(page.getByText('Narrow your sampling frame to two county offices.')).toBeVisible();await expect(page.getByRole('button',{name:'Apply to topic'})).toHaveCount(0)
})
test('document review gates approval on version specific similarity evidence',async({page})=>{
 await login(page,'student');await page.getByRole('button',{name:'My journey',exact:true}).click();await page.getByRole('navigation',{name:'Journey milestones'}).getByRole('button',{name:'Research proposal',exact:true}).click();await page.getByRole('button',{name:'Open milestone',exact:true}).click();await page.getByLabel('Submit document (PDF, DOCX, XLSX · 25 MB)').setInputFiles(path.resolve('../demo-fixtures/revised-proposal-demo.pdf'));await expect(page.getByText('Document submitted. Your receipt and version are saved.')).toBeVisible();await page.getByLabel('Attach similarity report').setInputFiles(path.resolve('../demo-fixtures/revised-proposal-demo.pdf'));await expect(page.getByText('Similarity evidence: Awaiting verification')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await switchUser(page,'supervisor');await page.getByRole('button',{name:'Reviews',exact:true}).click();await page.locator('.record-card').filter({hasText:'revised-proposal-demo.pdf'}).getByRole('button',{name:'Open review'}).click();await page.getByLabel('Decision',{exact:true}).selectOption('approved');await page.getByLabel('Feedback',{exact:true}).fill('The methodology is suitable for the proposed study.');await page.getByRole('button',{name:'Record decision'}).click();await expect(page.getByText('Verify the report for this exact version before approval.')).toBeVisible();await page.getByLabel('Similarity verification note').fill('External report reviewed against this exact version.');await page.getByRole('button',{name:'Verify evidence'}).click();await page.getByRole('button',{name:'Record decision'}).click();await expect(page.getByText('Academic decision recorded.')).toBeVisible()
})
test('three distinct dashboards and scoped filtered report export',async({page})=>{
 await login(page,'supervisor');await expect(page.getByRole('heading',{name:'Supervision workspace'})).toBeVisible();await expect(page.getByRole('heading',{name:'My students'})).toBeVisible();await switchUser(page,'dean');await expect(page.getByRole('heading',{name:'School oversight'})).toBeVisible();await expect(page.getByRole('heading',{name:'Progress by department'})).toBeVisible();await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByText('Lydia Wambui')).toHaveCount(0);await page.getByLabel('Student search').fill('Amina');await expect(page.locator('tbody tr')).toHaveCount(1);const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Export filtered CSV'}).click();expect((await downloadPromise).suggestedFilename()).toBe('progress-report.csv');await switchUser(page,'leadership');await expect(page.getByRole('heading',{name:'Graduate-school overview'})).toBeVisible();await expect(page.getByRole('heading',{name:'Progress by school'})).toBeVisible();await page.getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByText('Lydia Wambui')).toBeVisible()
})
test('pending student verification generates the part time programme plan',async({page})=>{
 await login(page,'newstudent');await page.getByRole('button',{name:'My enrolment',exact:true}).click();await page.getByRole('button',{name:'Open enrolment'}).click();await page.getByLabel('Programme',{exact:true}).selectOption('30000000-0000-0000-0000-000000000001');await page.getByLabel('Cohort',{exact:true}).selectOption('40000000-0000-0000-0000-000000000002');await page.getByLabel('Study mode',{exact:true}).selectOption('part_time');await page.getByLabel('Admission date').fill('2026-01-12');await page.getByRole('button',{name:'Submit for verification'}).click();await switchUser(page,'coordinator');await page.getByRole('button',{name:'Administration',exact:true}).click();await page.locator('.record-card').filter({hasText:'Brian Kiptoo'}).getByRole('button',{name:'Open enrolment'}).click();await page.getByLabel('Verification decision').selectOption('verified');await page.getByLabel('Plan start date').fill('2026-09-27');await page.getByLabel('Verification note').fill('Identity and programme confirmed against student record.');await page.getByRole('button',{name:'Record verification'}).click();await expect(page.getByText('Verification recorded.')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await switchUser(page,'newstudent');await page.getByRole('button',{name:'My journey',exact:true}).click();await expect(page.getByRole('heading',{name:'Part-time orientation',exact:true})).toBeVisible();await expect(page.locator('.journey-stage')).toHaveCount(4)
})
test('mobile request opens with keyboard dismissal',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByLabel('Email address').fill('student@demo.pac.test');await page.getByLabel('Password',{exact:true}).fill('Demo123!Change');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'Requests & support',exact:true}).click();await page.getByRole('button',{name:'Open request'}).first().click();await expect(page.getByRole('dialog',{name:'Request details'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()})
