import {useEffect,useState} from 'react'
import {Bell,Check,MessageSquareText} from 'lucide-react'
import {api,post,useData,Dialog,Form,Title,ErrorBox,Status,Empty,date,type Row} from './Workbench'

export function useNotifications(){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState('')
 useEffect(()=>{let alive=true;const refresh=()=>api('/notifications').then(r=>{if(alive){setRows(r);setError('')}}).catch(e=>{if(alive)setError(e.message)});void refresh();const timer=setInterval(refresh,10000);window.addEventListener('pac-notifications',refresh);return()=>{alive=false;clearInterval(timer);window.removeEventListener('pac-notifications',refresh)}},[])
 return {rows,error}
}
const changed=()=>window.dispatchEvent(new Event('pac-notifications'))
export function NotificationBell({open}:{open:()=>void}){const {rows}=useNotifications(),count=rows.filter(n=>!n.read&&!n.dismissed).length;return <button className="icon-button notification-bell" aria-label={count?'Notifications, '+count+' unread':'Notifications'} onClick={open}><Bell/>{count>0&&<span className="notification-count">{count>99?'99+':count}</span>}</button>}
export function NotificationInbox({navigate,openMilestone}:{navigate:(view:string)=>void;openMilestone:(id:string)=>void}){
 const {rows,error}=useNotifications(),[failure,setFailure]=useState(''),[busy,setBusy]=useState('')
 async function act(n:Row,action:string){setBusy(n.id);setFailure('');try{await post('/notifications/'+n.id+'/'+action,{});changed()}catch(e){setFailure((e as Error).message);throw e}finally{setBusy('')}}
 return <><Title title="Notifications" subtitle="In-app updates refresh every 10 seconds. Email delivery is deferred."/><ErrorBox message={error||failure}/>{rows.filter(n=>!n.dismissed).map(n=><article className={'record-card notification-card '+(!n.read?'unread':'')} key={n.id}><div className="student-section-heading"><h2>{n.title}</h2><Status value={n.read?'read':'unread'}/></div><p>{new Date(n.updatedAt).toLocaleString('en-KE')}</p>{n.body&&<p className="preserve-lines">{n.body}</p>}<div className="student-actions">{!n.read&&<button className="secondary" disabled={!!busy} onClick={()=>void act(n,'read').catch(()=>{})}>Mark read</button>}<button className="secondary" disabled={!!busy} onClick={()=>void act(n,'dismiss').catch(()=>{})}>Dismiss</button>{(n.target_view||n.milestone_id)&&<button className="primary" disabled={!!busy} onClick={async()=>{try{await act(n,'read');n.milestone_id?openMilestone(n.milestone_id):navigate(n.target_view)}catch{}}}>Open related work</button>}</div></article>)}{!rows.some(n=>!n.dismissed)&&<Empty>No notifications yet. New replies and workflow updates will appear here.</Empty>}</>
}
export function FollowupComposer({student,close}:{student:Row;close:()=>void}){
 return <Dialog title={'Follow up · '+student.student} close={close}><FollowupThread student={student}/></Dialog>
}
function FollowupThread({student}:{student:Row}){
 const people=useData('/enrolments/'+student.id+'/contacts'),q=useData('/enrolments/'+student.id+'/followups'),me=useData('/me'),[sent,setSent]=useState('')
 useEffect(()=>{const timer=setInterval(q.reload,10000);return()=>clearInterval(timer)},[student.id])
 const contacts:Row[]=(people.data||[]).filter((x:Row)=>x.id!==me.data?.ID),owner=contacts.find(x=>x.needs_action)
 return <><p>Send an in-app follow-up to the person responsible. Only you and the recipient see the message; academic records remain in the milestone discussion.</p><p className="student-muted">Email to IT, finance and external departments is deferred. No email will be sent.</p><ErrorBox message={q.error||people.error}/>{sent&&<p role="status" className="student-notice calm">{sent}</p>}{contacts.length>0?<Form key={student.id+contacts.map(x=>x.id).join(',')} initial={{RecipientID:owner?.id||contacts[0].id}} fields={[{key:'RecipientID',label:'Send to',options:contacts.map(x=>({value:x.id,label:x.full_name+' · '+x.email+(x.needs_action?' · action pending':'')}))},{key:'Body',label:'Follow-up message',type:'textarea'}]} label="Send in-app notification" submit={async v=>{await post('/enrolments/'+student.id+'/followups',v);setSent('Sent in-app. The recipient can read and reply in Follow-ups.');q.reload();changed()}}/>:<Empty>No other authorized participant available.</Empty>}<h3>Your conversation history</h3>{(q.data||[]).map((m:Row)=><article className="message" key={m.id}><b>{m.sender} → {m.recipient}</b><small>{new Date(m.created_at).toLocaleString('en-KE')}</small><p className="preserve-lines">{m.body}</p></article>)}{q.data?.length===0&&<p>No follow-ups sent or received yet.</p>}</>
}
export function FollowupInbox(){const q=useData('/workspace/students'),[id,setId]=useState(''),student=(q.data||[]).find((s:Row)=>s.id===id)||q.data?.[0];return <><Title title="Follow-ups" subtitle="Direct messages to authorized people responsible for the next step."/><ErrorBox message={q.error}/><label>Student<select aria-label="Follow-up student" value={student?.id||''} onChange={e=>setId(e.target.value)}>{(q.data||[]).map((s:Row)=><option key={s.id} value={s.id}>{s.student}</option>)}</select></label>{student?<FollowupThread key={student.id} student={student}/>:<Empty>No student records in your scope.</Empty>}</>}
export function Discussion({milestoneId}:{milestoneId:string}){
 const students=useData('/workspace/students'),milestones=useData('/workspace/milestones'),q=useData('/milestones/'+milestoneId+'/detail'),[body,setBody]=useState(''),[version,setVersion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false)
 useEffect(()=>{const timer=setInterval(q.reload,10000);return()=>clearInterval(timer)},[milestoneId])
 return <section className="academic-discussion"><h3><MessageSquareText size={18}/> Submission discussion</h3><p className="student-muted">Shared with the student and authorized academic staff. Replies refresh every 10 seconds. Use private support for welfare matters.</p><ErrorBox message={q.error||error}/><div className="discussion-messages" aria-label="Discussion messages">{(q.data?.comments||[]).map((c:Row)=><article className="message" key={c.id}><b>{c.author}</b><small>{new Date(c.created_at).toLocaleString('en-KE')} · {c.submission_version_id?'Version '+(q.data.versions.find((v:Row)=>v.id===c.submission_version_id)?.version||'record'):'Milestone discussion'}</small><p className="preserve-lines">{c.body}</p></article>)}{q.data?.comments?.length===0&&<p>No comments yet. Ask a question or share academic feedback.</p>}</div><form className="workflow-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSent(false);try{await post('/milestones/'+milestoneId+'/comments',{Body:body,VersionID:version});setBody('');setSent(true);q.reload();changed()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Discussion context<select value={version} onChange={e=>setVersion(e.target.value)}><option value="">General milestone discussion</option>{(q.data?.versions||[]).map((v:Row)=><option key={v.id} value={v.id}>Version {v.version} · {v.original_name}</option>)}</select></label><label>Academic question or comment<textarea required minLength={2} maxLength={4000} value={body} onChange={e=>setBody(e.target.value)} rows={3}/></label><button className="primary" disabled={busy}>{busy?'Posting…':'Post comment'}</button>{sent&&<p role="status">Comment posted. Other participants have been notified in-app.</p>}</form>{students.data&&milestones.data&&(()=>{const m=milestones.data.find((m:Row)=>m.id===milestoneId),student=students.data.find((s:Row)=>s.id===m?.enrolment_id);return student?<details className="discussion-referral"><summary>Refer this discussion / follow up with the academic team</summary><FollowupThread student={student}/></details>:null})()}</section>
}
export function GroupProgress({rows}:{rows:Row[]}){const total=rows.reduce((n,s)=>n+Number(s.total),0),done=rows.reduce((n,s)=>n+Number(s.completed),0),percent=total?Math.round(done/total*100):0;return <div className="group-progress"><span>{percent}% of recorded milestones complete</span><progress value={done} max={total||1}/></div>}
export function GroupedJourney({notify,initialId}:{notify:(s:string)=>void;initialId?:string}){
 const q=useData('/workspace/milestones'),students=useData('/workspace/students'),concepts=useData('/concepts'),[selected,setSelected]=useState<Row|null>(null)
 useEffect(()=>{if(initialId&&q.data)setSelected(q.data.find((m:Row)=>m.id===initialId)||null)},[initialId,q.data])
 // Full milestone dialog is rendered by the parent to retain academic controls.
 return <><Title title="Student milestones" subtitle="Students A–Z. Expand a student to see their complete research journey."/><ErrorBox message={q.error||students.error}/>{(students.data||[]).map((s:Row)=>{const ms:Row[]=(q.data||[]).filter((m:Row)=>m.enrolment_id===s.id),concept=(concepts.data||[]).find((c:Row)=>c.enrolment_id===s.id),percent=ms.length?Math.round(ms.filter(m=>m.state==='approved').length/ms.length*100):0;return <details className="student-group record-card" key={s.id} open={initialId&&ms.some(m=>m.id===initialId)?true:undefined}><summary><span className="compact-ring" style={{background:`conic-gradient(#17664f ${percent}%,#e8eeea 0)`}}><span>{percent}%</span></span><span><strong>{s.student}</strong><small>{s.programme} · {s.stage||'Awaiting programme setup'}</small></span><span className="expand-hint">View milestones</span></summary>{concept&&<p>Research concept: {concept.title} · {concept.state.replaceAll('_',' ')}</p>}<div className="group-milestones">{ms.map(m=><article className="message" key={m.id}><div className="student-section-heading"><h3>{m.title}</h3><Status value={m.state}/></div><p>Due {date(m.current_due)}</p><button className="secondary" onClick={()=>setSelected(m)}>Open milestone</button></article>)}</div>{!ms.length&&<p>Contact the programme office to link this student's research plan.</p>}</details>})}{selected&&<AcademicRecord milestone={selected} close={()=>setSelected(null)} notify={notify}/>}</>
}
import {MilestoneDetail} from './Workbench'
function AcademicRecord({milestone,close,notify}:{milestone:Row;close:()=>void;notify:(s:string)=>void}){const me=useData('/me');return <MilestoneDetail role={me.data?.Roles?.some((r:Row)=>r.Name==='supervisor')?'supervisor':'staff'} milestone={milestone} close={close} notify={notify}/>}
